version: "3.9"

services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    expose:
      - 5672:5672
      - 15672:15672

  redis:
    image: 'redis/redis-stack'
    expose:
      - 6379:6379
      - 8001:8001

  client:
    build: ./client
    ports:
      - 5000:5000
    environment:
      - secret='your-secret'
    depends_on:
      - rabbitmq
      - redis

  server:
    build: ./server
    depends_on:
      - rabbitmq
      - redis
    restart: on-failure

